language: python

python: 3.5

env:
  - TOX_ENV=py35-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py27-django110
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py27-django18
  - TOX_ENV=flake8
  - TOX_ENV=docs

install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox"

script:
  - tox -e $TOX_ENV

after_script:
  - cat .tox/$TOX_ENV/log/*.log
